# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.31.15:3306/sparrowDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

# mybatis 配置
mybatis:
  config-location: classpath:db/mybatis/config.xml

sparrowShop:
  redis:
    host: 192.168.31.15
    port: 6379