package com.xdc.sparrowShop.generate;

import com.xdc.sparrowShop.generate.Area;
import com.xdc.sparrowShop.generate.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    long countByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int deleteByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    List<Area> selectByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByPrimaryKey(Area record);
}