package com.xdc.sparrowShop.generate;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA.CITY_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA.ID
     *
     * @return the value of AREA.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA.ID
     *
     * @param id the value for AREA.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA.NAME
     *
     * @return the value of AREA.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA.NAME
     *
     * @param name the value for AREA.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA.CITY_ID
     *
     * @return the value of AREA.CITY_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA.CITY_ID
     *
     * @param cityId the value for AREA.CITY_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}