package com.xdc.sparrowShop.generate;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.PROVINCE_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer provinceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.ID
     *
     * @return the value of CITY.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.ID
     *
     * @param id the value for CITY.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.NAME
     *
     * @return the value of CITY.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.NAME
     *
     * @param name the value for CITY.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.PROVINCE_ID
     *
     * @return the value of CITY.PROVINCE_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.PROVINCE_ID
     *
     * @param provinceId the value for CITY.PROVINCE_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
}