package com.xdc.sparrowShop.generate;

import java.util.Date;

public class Fresh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.TYPE_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.SHOP_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.AREA_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.DESCRIPTION
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.PICTURE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.STOCK
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.STATUS
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.CREATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.UPDATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH.count
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.ID
     *
     * @return the value of FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.ID
     *
     * @param id the value for FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.TYPE_ID
     *
     * @return the value of FRESH.TYPE_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.TYPE_ID
     *
     * @param typeId the value for FRESH.TYPE_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.SHOP_ID
     *
     * @return the value of FRESH.SHOP_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.SHOP_ID
     *
     * @param shopId the value for FRESH.SHOP_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.AREA_ID
     *
     * @return the value of FRESH.AREA_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.AREA_ID
     *
     * @param areaId the value for FRESH.AREA_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.NAME
     *
     * @return the value of FRESH.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.NAME
     *
     * @param name the value for FRESH.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.DESCRIPTION
     *
     * @return the value of FRESH.DESCRIPTION
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.DESCRIPTION
     *
     * @param description the value for FRESH.DESCRIPTION
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.PICTURE
     *
     * @return the value of FRESH.PICTURE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.PICTURE
     *
     * @param picture the value for FRESH.PICTURE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.PRICE
     *
     * @return the value of FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.PRICE
     *
     * @param price the value for FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.STOCK
     *
     * @return the value of FRESH.STOCK
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.STOCK
     *
     * @param stock the value for FRESH.STOCK
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.STATUS
     *
     * @return the value of FRESH.STATUS
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.STATUS
     *
     * @param status the value for FRESH.STATUS
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.CREATED_AT
     *
     * @return the value of FRESH.CREATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.CREATED_AT
     *
     * @param createdAt the value for FRESH.CREATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.UPDATED_AT
     *
     * @return the value of FRESH.UPDATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.UPDATED_AT
     *
     * @param updatedAt the value for FRESH.UPDATED_AT
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH.count
     *
     * @return the value of FRESH.count
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH.count
     *
     * @param count the value for FRESH.count
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}