package com.xdc.sparrowShop.generate;

import com.xdc.sparrowShop.generate.Fresh;
import com.xdc.sparrowShop.generate.FreshExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FreshMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    long countByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int deleteByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int insert(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int insertSelective(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    List<Fresh> selectByExample(FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    Fresh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") Fresh record, @Param("example") FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByExample(@Param("record") Fresh record, @Param("example") FreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByPrimaryKeySelective(Fresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRESH
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByPrimaryKey(Fresh record);
}