package com.xdc.sparrowShop.generate;

public class FreshType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH_TYPE.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRESH_TYPE.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH_TYPE.ID
     *
     * @return the value of FRESH_TYPE.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH_TYPE.ID
     *
     * @param id the value for FRESH_TYPE.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRESH_TYPE.NAME
     *
     * @return the value of FRESH_TYPE.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRESH_TYPE.NAME
     *
     * @param name the value for FRESH_TYPE.NAME
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}