package com.xdc.sparrowShop.generate;

import java.util.Date;

public class MyOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.USER_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.SHOP_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.TOTAL_MONEY
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.ADDRESS_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_ORDER.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.ID
     *
     * @return the value of MY_ORDER.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.ID
     *
     * @param id the value for MY_ORDER.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.USER_ID
     *
     * @return the value of MY_ORDER.USER_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.USER_ID
     *
     * @param userId the value for MY_ORDER.USER_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.SHOP_ID
     *
     * @return the value of MY_ORDER.SHOP_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.SHOP_ID
     *
     * @param shopId the value for MY_ORDER.SHOP_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.TOTAL_MONEY
     *
     * @return the value of MY_ORDER.TOTAL_MONEY
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.TOTAL_MONEY
     *
     * @param totalMoney the value for MY_ORDER.TOTAL_MONEY
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setTotalMoney(Integer totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.ADDRESS_ID
     *
     * @return the value of MY_ORDER.ADDRESS_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.ADDRESS_ID
     *
     * @param addressId the value for MY_ORDER.ADDRESS_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.STATUS
     *
     * @return the value of MY_ORDER.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.STATUS
     *
     * @param status the value for MY_ORDER.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.CREATED_AT
     *
     * @return the value of MY_ORDER.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.CREATED_AT
     *
     * @param createdAt the value for MY_ORDER.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_ORDER.UPDATED_AT
     *
     * @return the value of MY_ORDER.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_ORDER.UPDATED_AT
     *
     * @param updatedAt the value for MY_ORDER.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}