package com.xdc.sparrowShop.generate;

import com.xdc.sparrowShop.generate.OrderFresh;
import com.xdc.sparrowShop.generate.OrderFreshExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderFreshMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    long countByExample(OrderFreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int deleteByExample(OrderFreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int insert(OrderFresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int insertSelective(OrderFresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    List<OrderFresh> selectByExample(OrderFreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    OrderFresh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderFresh record, @Param("example") OrderFreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByExample(@Param("record") OrderFresh record, @Param("example") OrderFreshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByPrimaryKeySelective(OrderFresh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_FRESH
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    int updateByPrimaryKey(OrderFresh record);
}