package com.xdc.sparrowShop.generate;

public class OrderFresh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_FRESH.ORDER_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_FRESH.FRESH_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer freshId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_FRESH.amount
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_FRESH.ID
     *
     * @return the value of ORDER_FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_FRESH.ID
     *
     * @param id the value for ORDER_FRESH.ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_FRESH.ORDER_ID
     *
     * @return the value of ORDER_FRESH.ORDER_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_FRESH.ORDER_ID
     *
     * @param orderId the value for ORDER_FRESH.ORDER_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_FRESH.FRESH_ID
     *
     * @return the value of ORDER_FRESH.FRESH_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getFreshId() {
        return freshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_FRESH.FRESH_ID
     *
     * @param freshId the value for ORDER_FRESH.FRESH_ID
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setFreshId(Integer freshId) {
        this.freshId = freshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_FRESH.amount
     *
     * @return the value of ORDER_FRESH.amount
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_FRESH.amount
     *
     * @param amount the value for ORDER_FRESH.amount
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_FRESH.PRICE
     *
     * @return the value of ORDER_FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_FRESH.PRICE
     *
     * @param price the value for ORDER_FRESH.PRICE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}