package com.xdc.sparrowShop.generate;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVINCE.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVINCE.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVINCE.ID
     *
     * @return the value of PROVINCE.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVINCE.ID
     *
     * @param id the value for PROVINCE.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVINCE.NAME
     *
     * @return the value of PROVINCE.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVINCE.NAME
     *
     * @param name the value for PROVINCE.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}