package com.xdc.sparrowShop.generate;

import com.xdc.sparrowShop.generate.Province;
import com.xdc.sparrowShop.generate.ProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    long countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    Province selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVINCE
     *
     * @mbg.generated Thu May 07 23:28:16 CST 2020
     */
    int updateByPrimaryKey(Province record);
}