package com.xdc.sparrowShop.generate;

import java.util.Date;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.AREA_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.LOGO
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.PHONE
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.SHOP_KEEPER
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String shopKeeper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.PASSWORD
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.DESCRIPTION
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.ID
     *
     * @return the value of SHOP.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.ID
     *
     * @param id the value for SHOP.ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.AREA_ID
     *
     * @return the value of SHOP.AREA_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.AREA_ID
     *
     * @param areaId the value for SHOP.AREA_ID
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.NAME
     *
     * @return the value of SHOP.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.NAME
     *
     * @param name the value for SHOP.NAME
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.LOGO
     *
     * @return the value of SHOP.LOGO
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.LOGO
     *
     * @param logo the value for SHOP.LOGO
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.PHONE
     *
     * @return the value of SHOP.PHONE
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.PHONE
     *
     * @param phone the value for SHOP.PHONE
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.SHOP_KEEPER
     *
     * @return the value of SHOP.SHOP_KEEPER
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getShopKeeper() {
        return shopKeeper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.SHOP_KEEPER
     *
     * @param shopKeeper the value for SHOP.SHOP_KEEPER
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setShopKeeper(String shopKeeper) {
        this.shopKeeper = shopKeeper == null ? null : shopKeeper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.STATUS
     *
     * @return the value of SHOP.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.STATUS
     *
     * @param status the value for SHOP.STATUS
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.PASSWORD
     *
     * @return the value of SHOP.PASSWORD
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.PASSWORD
     *
     * @param password the value for SHOP.PASSWORD
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.DESCRIPTION
     *
     * @return the value of SHOP.DESCRIPTION
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.DESCRIPTION
     *
     * @param description the value for SHOP.DESCRIPTION
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.CREATED_AT
     *
     * @return the value of SHOP.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.CREATED_AT
     *
     * @param createdAt the value for SHOP.CREATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP.UPDATED_AT
     *
     * @return the value of SHOP.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP.UPDATED_AT
     *
     * @param updatedAt the value for SHOP.UPDATED_AT
     *
     * @mbg.generated Sat May 02 15:12:52 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}