create table FRESH_TYPE
(
    ID int auto_increment,
    NAME VARCHAR(20) not null,
    constraint FRESH_TYPE_pk
        primary key (ID)
)
    comment '生鲜类别表';

create unique index FRESH_TYPE_NAME_uindex
    on FRESH_TYPE (NAME);

INSERT INTO FRESH_TYPE(NAME) VALUES ('水果');
INSERT INTO FRESH_TYPE(NAME) VALUES ('蔬菜');
INSERT INTO FRESH_TYPE(NAME) VALUES ('肉禽');
INSERT INTO FRESH_TYPE(NAME) VALUES ('蛋类');
INSERT INTO FRESH_TYPE(NAME) VALUES ('海鲜');
INSERT INTO FRESH_TYPE(NAME) VALUES ('粮油');
INSERT INTO FRESH_TYPE(NAME) VALUES ('酒水');
INSERT INTO FRESH_TYPE(NAME) VALUES ('乳品');
INSERT INTO FRESH_TYPE(NAME) VALUES ('烘培');
INSERT INTO FRESH_TYPE(NAME) VALUES ('零食');
